# https://dart.dev/tools/linter-rules

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    unnecessary_parenthesis: true
    sort_constructors_first: true
    require_trailing_commas: true
