name: example
description: An example project for Flutter Pie Menu.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pie_menu:
    path: ../

  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  flutter_bounceable: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
